apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: install-config-secret
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    {{- $vc := (lookup "v1" "Secret" "cluster-provider-infra" "aws-creds") }}
    {{- $installConfig := `
    apiVersion: v1
    baseDomain: %[1]s
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: worker
      replicas: 2
      platform:
        aws:
          rootVolume:
            iops: 2000
            size: 100
            type: io1
          type: m5.xlarge
          zones:
          - ap-southeast-1a
          - ap-southeast-1b
          - ap-southeast-1c
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform:
        aws:
          zones:
          - eu-west-1a 
          - eu-west-1b 
          - eu-west-1c 
          rootVolume:
            iops: 4000
            size: 500
            type: io1 
          type: m5.2xlarge
    metadata:
      name: bry
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      aws:
        region: ap-southeast-1
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: %[2]s`
    }}
    
    {{- /* create the secret using the thanos configuration template created above. */ -}}
    - complianceType: mustonlyhave
      objectDefinition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: install-config
          namespace: bry
        data:
          install-config.yaml: {{ (printf $installConfig ($vc.data.baseDomain | base64dec)
                                                          (index $vc.data "ssh-publickey" | base64dec )
                                  ) | base64enc }}
