apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


## specify the namespace to match the name of the cluster.
## this set the namespace on objects included in the policy, not the policy itself
namespace: meggen-lab


## include any additional objects that should be part of the policy
resources:
  - ../../base/aws/

## Set cluster values for clusterset and imageset.
## If you want a custom ImageSet - add a custome file to resources above and set the name below
## The transformer below includes these values in the final policy
## NOTE the worker MachinePool must be named ClusterName-worker.  
##     This is set in workerMPName below
generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
  - name: set-cluster-values
    literals:
    - workerMPName=meggen-worker
    - region=eu-west-1
    - clusterSet=dev-clusters
    - imageSetRefName=img4.15.17-multi
    - autoScaleMaxWorkerNodes=5


## patch the managed cluster to define cluster specific lables
patches:
  - target:
      kind: ManagedCluster
    path: managedcluster.yml

  - target:
      kind: MachinePool
    path: worker-machinepool.yml


transformers:
  - ../../base/common/kustomize-configs/
  - ../../base/common/kustomize-configs/aws/

